sudo: false
language: python
install: pip install tox

matrix:
  include:
  - python: "2.6"
    env: TOX_ENV=py26
  - python: "2.7"
    env: TOX_ENV=py27
  - python: "3.5"
    env: TOX_ENV=cov-travis
  - python: "3.5"
    env: TOX_ENV=static
  - python: "3.5"
    env: TOX_ENV=docs
script: tox -e $TOX_ENV

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  verbose: true
  local-dir: docs/more_executors
  on:
    repo: rohanpm/more-executors
    branch: master
    condition: $TOX_ENV = docs
